### ISSUE TITLE
g++: internal compiler error: Memory access error (program cc1plus)

### ISSUE THREAD

**Issue by MTRNord** [SpiderOak/crypton#370]
Hello i have this error when i am running npm link in the server dir on the Raspberry pi2.
Full Debug Code is (sorry it is sometimes German):
```
root@RPIMarcel2:/home/pi/crypton/server# npm link --unsafe-perm --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'link',
npm verb cli   '--unsafe-perm',
npm verb cli   '--verbose' ]
npm info using npm@1.4.28
npm info using node@v0.10.40
npm verb node symlink /usr/bin/node
npm verb linkPkg /home/pi/crypton/server
npm verb link build target /usr/lib/node_modules/crypton-server
npm verb install where,what [ '/home/pi/crypton/server', [] ]
npm verb readDependencies using package.json deps
npm verb install where, deps [ '/home/pi/crypton/server',
npm verb install   [ 'bcrypt',
npm verb install     'colors',
npm verb install     'commander',
npm verb install     'connect',
npm verb install     'connect-redis',
npm verb install     'cookie',
npm verb install     'cookies',
npm verb install     'cors',
npm verb install     'cryptojs',
npm verb install     'express',
npm verb install     'forever',
npm verb install     'lusca',
npm verb install     'node-uuid',
npm verb install     'pg',
npm verb install     'pg-native',
npm verb install     'redis',
npm verb install     'semver',
npm verb install     'socket.io',
npm verb install     'srp',
npm verb install     'validator',
npm verb install     'mocha',
npm verb install     'should',
npm verb install     'sinon',
npm verb install     'mockery' ] ]
npm info preinstall crypton-server@0.0.4
npm verb readDependencies using package.json deps
npm verb already installed skipping cookies@0.5.x /home/pi/crypton/server
npm verb already installed skipping cors@~2.1.1 /home/pi/crypton/server
npm verb already installed skipping cryptojs@2.5.x /home/pi/crypton/server
npm verb already installed skipping express@3.5.x /home/pi/crypton/server
npm verb already installed skipping forever@^0.11.1 /home/pi/crypton/server
npm verb already installed skipping lusca@1.0.x /home/pi/crypton/server
npm verb already installed skipping node-uuid@1.4.x /home/pi/crypton/server
npm verb already installed skipping pg@4.3.x /home/pi/crypton/server
npm verb already installed skipping pg-native@1.8.x /home/pi/crypton/server
npm verb already installed skipping redis@~0.8.4 /home/pi/crypton/server
npm verb already installed skipping semver@^4.2.0 /home/pi/crypton/server
npm verb already installed skipping socket.io@1.3.x /home/pi/crypton/server
npm verb cache add [ 'srp@git+https://github.com/daviddahl/node-srp.git', null ]
npm verb cache add name=undefined spec="srp@git+https://github.com/daviddahl/node-srp.git" args=["srp@git+https://github.com/daviddahl/node-srp.git",null]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: 'srp@git+https://github.com/daviddahl/node-srp.git',
npm verb parsed url   path: 'srp@git+https://github.com/daviddahl/node-srp.git',
npm verb parsed url   href: 'srp@git+https://github.com/daviddahl/node-srp.git' }
npm verb already installed skipping validator@3.5.x /home/pi/crypton/server
npm verb already installed skipping mocha@1.8.x /home/pi/crypton/server
npm verb already installed skipping should@1.2.x /home/pi/crypton/server
npm verb already installed skipping sinon@1.5.x /home/pi/crypton/server
npm verb already installed skipping mockery@1.4.x /home/pi/crypton/server
npm verb already installed skipping bcrypt@0.8.x /home/pi/crypton/server
npm verb already installed skipping colors@0.6.x /home/pi/crypton/server
npm verb already installed skipping commander@1.1.x /home/pi/crypton/server
npm verb already installed skipping connect@2.7.x /home/pi/crypton/server
npm verb already installed skipping connect-redis@~1.4.5 /home/pi/crypton/server
npm verb already installed skipping cookie@0.1.x /home/pi/crypton/server
npm verb cache add name="srp" spec="git+https://github.com/daviddahl/node-srp.git" args=["srp","git+https://github.com/daviddahl/node-srp.git"]
npm verb parsed url { protocol: 'git+https:',
npm verb parsed url   slashes: true,
npm verb parsed url   auth: null,
npm verb parsed url   host: 'github.com',
npm verb parsed url   port: null,
npm verb parsed url   hostname: 'github.com',
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: '/daviddahl/node-srp.git',
npm verb parsed url   path: '/daviddahl/node-srp.git',
npm verb parsed url   href: 'git+https://github.com/daviddahl/node-srp.git' }
npm verb lock https://github.com/daviddahl/node-srp.git /root/.npm/f76308b2-ithub-com-daviddahl-node-srp-git.lock
npm verb addRemoteGit [ 'https://github.com/daviddahl/node-srp.git', 'master' ]
npm verb git remote.origin.url https://github.com/daviddahl/node-srp.git
npm verb git fetch -a origin (https://github.com/daviddahl/node-srp.git) 
npm verb git rev-list -n1 master 40b73c21c2ef5a8fada502883ca45d07accf128d
npm verb resolved git url git+https://github.com/daviddahl/node-srp.git#40b73c21c2ef5a8fada502883ca45d07accf128d
npm verb tar unpack /tmp/npm-21511-x1VToOyf/1439498209835-0.06269975239410996/tmp.tgz
npm verb lock tar:///tmp/npm-21511-x1VToOyf/1439498209835-0.06269975239410996/tmp.tgz-unpack /root/.npm/3555e539-06269975239410996-tmp-tgz-unpack.lock
npm verb lock tar:///tmp/npm-21511-x1VToOyf/1439498209835-0.06269975239410996/tmp.tgz /root/.npm/538f66c9-9835-0-06269975239410996-tmp-tgz.lock
npm info install srp@0.2.0 into /home/pi/crypton/server
npm info installOne srp@0.2.0
npm verb node_modules/srp unbuild
npm verb tar unpack /root/.npm/srp/0.2.0/package.tgz
npm verb lock tar:///home/pi/crypton/server/node_modules/srp /root/.npm/c5cbc3da--crypton-server-node-modules-srp.lock
npm verb lock tar:///root/.npm/srp/0.2.0/package.tgz /root/.npm/b023c721-r-root-npm-srp-0-2-0-package-tgz.lock
npm info preinstall srp@0.2.0
npm verb readDependencies using package.json deps
npm verb readDependencies using package.json deps
npm verb cache add [ 'bignum@0.9.x', null ]
npm verb cache add name=undefined spec="bignum@0.9.x" args=["bignum@0.9.x",null]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: 'bignum@0.9.x',
npm verb parsed url   path: 'bignum@0.9.x',
npm verb parsed url   href: 'bignum@0.9.x' }
npm verb cache add name="bignum" spec="0.9.x" args=["bignum","0.9.x"]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: '0.9.x',
npm verb parsed url   path: '0.9.x',
npm verb parsed url   href: '0.9.x' }
npm verb addNamed [ 'bignum', '0.9.x' ]
npm verb addNamed [ null, '>=0.9.0-0 <0.10.0-0' ]
npm verb lock bignum@0.9.x /root/.npm/16cb1be3-bignum-0-9-x.lock
npm verb request where is /bignum
npm verb request registry https://registry.npmjs.org/
npm verb request id b83d9c7aaa0d23d6
npm verb url raw /bignum
npm verb url resolving [ 'https://registry.npmjs.org/', './bignum' ]
npm verb url resolved https://registry.npmjs.org/bignum
npm verb request where is https://registry.npmjs.org/bignum
npm info trying registry request attempt 1 at 22:36:54
npm verb etag "4NWV6X38UP2Q8T1YIVPNTQKKY"
npm http GET https://registry.npmjs.org/bignum
npm http 304 https://registry.npmjs.org/bignum
npm verb etag https://registry.npmjs.org/bignum from cache
npm verb addNamed [ 'bignum', '0.9.3' ]
npm verb addNamed [ '0.9.3', '0.9.3' ]
npm verb lock bignum@0.9.3 /root/.npm/affb33ba-bignum-0-9-3.lock
npm info install bignum@0.9.3 into /home/pi/crypton/server/node_modules/srp
npm info installOne bignum@0.9.3
npm verb node_modules/srp/node_modules/bignum unbuild
npm verb tar unpack /root/.npm/bignum/0.9.3/package.tgz
npm verb lock tar:///home/pi/crypton/server/node_modules/srp/node_modules/bignum /root/.npm/89e649ad--modules-srp-node-modules-bignum.lock
npm verb lock tar:///root/.npm/bignum/0.9.3/package.tgz /root/.npm/9d1676bd-oot-npm-bignum-0-9-3-package-tgz.lock
npm info preinstall bignum@0.9.3
npm verb readDependencies using package.json deps
npm verb readDependencies using package.json deps
npm verb cache add [ 'nan@~1.8.4', null ]
npm verb cache add name=undefined spec="nan@~1.8.4" args=["nan@~1.8.4",null]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: 'nan@~1.8.4',
npm verb parsed url   path: 'nan@~1.8.4',
npm verb parsed url   href: 'nan@~1.8.4' }
npm verb cache add name="nan" spec="~1.8.4" args=["nan","~1.8.4"]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: '~1.8.4',
npm verb parsed url   path: '~1.8.4',
npm verb parsed url   href: '~1.8.4' }
npm verb addNamed [ 'nan', '~1.8.4' ]
npm verb addNamed [ null, '>=1.8.4-0 <1.9.0-0' ]
npm verb lock nan@~1.8.4 /root/.npm/0a5ed386-nan-1-8-4.lock
npm verb request where is /nan
npm verb request registry https://registry.npmjs.org/
npm verb url raw /nan
npm verb url resolving [ 'https://registry.npmjs.org/', './nan' ]
npm verb url resolved https://registry.npmjs.org/nan
npm verb request where is https://registry.npmjs.org/nan
npm info trying registry request attempt 1 at 22:36:58
npm verb etag "41PIK59ZUA3ADEJCQ281I0TDQ"
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm verb etag https://registry.npmjs.org/nan from cache
npm verb addNamed [ 'nan', '1.8.4' ]
npm verb addNamed [ '1.8.4', '1.8.4' ]
npm verb lock nan@1.8.4 /root/.npm/86d5700b-nan-1-8-4.lock
npm info install nan@1.8.4 into /home/pi/crypton/server/node_modules/srp/node_modules/bignum
npm info installOne nan@1.8.4
npm verb node_modules/srp/node_modules/bignum/node_modules/nan unbuild
npm verb tar unpack /root/.npm/nan/1.8.4/package.tgz
npm verb lock tar:///home/pi/crypton/server/node_modules/srp/node_modules/bignum/node_modules/nan /root/.npm/6c3061b1--modules-bignum-node-modules-nan.lock
npm verb lock tar:///root/.npm/nan/1.8.4/package.tgz /root/.npm/2748c7d4-r-root-npm-nan-1-8-4-package-tgz.lock
npm info preinstall nan@1.8.4
npm verb readDependencies using package.json deps
npm verb readDependencies using package.json deps
npm verb about to build /home/pi/crypton/server/node_modules/srp/node_modules/bignum/node_modules/nan
npm info build /home/pi/crypton/server/node_modules/srp/node_modules/bignum/node_modules/nan
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   '/home/pi/crypton/server/node_modules/srp/node_modules/bignum/node_modules' ]
npm info linkStuff nan@1.8.4
npm verb linkBins nan@1.8.4
npm verb linkMans nan@1.8.4
npm verb rebuildBundles nan@1.8.4
npm info install nan@1.8.4
npm info postinstall nan@1.8.4
npm verb about to build /home/pi/crypton/server/node_modules/srp/node_modules/bignum
npm info build /home/pi/crypton/server/node_modules/srp/node_modules/bignum
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   '/home/pi/crypton/server/node_modules/srp/node_modules' ]
npm info linkStuff bignum@0.9.3
npm verb linkBins bignum@0.9.3
npm verb linkMans bignum@0.9.3
npm verb rebuildBundles bignum@0.9.3
npm verb rebuildBundles [ 'nan' ]
npm info install bignum@0.9.3

> bignum@0.9.3 install /home/pi/crypton/server/node_modules/srp/node_modules/bignum
> node-gyp configure build

gyp info it worked if it ends with ok
gyp verb cli [ 'node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   'build' ]
gyp info using node-gyp@1.0.1
gyp info using node@0.10.40 | linux | arm
gyp verb command configure []
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `python -c "import platform; print(platform.python_version());"` returned: "2.7.3\n"
gyp verb get node dir no --target version specified, falling back to host node version: v0.10.40
gyp verb command install [ 'v0.10.40' ]
gyp verb install input version string "v0.10.40"
gyp verb install installing version: 0.10.40
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 0.10.40
gyp verb build dir attempting to create "build" dir: /home/pi/crypton/server/node_modules/srp/node_modules/bignum/build
gyp verb build dir "build" dir needed to be created? /home/pi/crypton/server/node_modules/srp/node_modules/bignum/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/pi/crypton/server/node_modules/srp/node_modules/bignum/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/pi/crypton/server/node_modules/srp/node_modules/bignum/config.gypi
gyp verb common.gypi checking for gypi file: /home/pi/crypton/server/node_modules/srp/node_modules/bignum/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn python
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/crypton/server/node_modules/srp/node_modules/bignum/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/0.10.40/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.10.40',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/crypton/server/node_modules/srp/node_modules/bignum',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm
gyp verb node dev dir /root/.node-gyp/0.10.40
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/crypton/server/node_modules/srp/node_modules/bignum/build'
  g++ '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/root/.node-gyp/0.10.40/src -I/root/.node-gyp/0.10.40/deps/uv/include -I/root/.node-gyp/0.10.40/deps/v8/include -I../node_modules/nan -I/root/.node-gyp/0.10.40/deps/openssl/openssl/include -I/root/.node-gyp/0.10.40/deps/openssl/config/arm  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -O2 -fno-strict-aliasing -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF ./Release/.deps/Release/obj.target/bignum/bignum.o.d.raw  -c -o Release/obj.target/bignum/bignum.o ../bignum.cc
g++: internal compiler error: Speicherzugriffsfehler (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
bignum.target.mk:86: recipe for target 'Release/obj.target/bignum/bignum.o' failed
make: *** [Release/obj.target/bignum/bignum.o] Error 4
make: Leaving directory '/home/pi/crypton/server/node_modules/srp/node_modules/bignum/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.0.8-v7+
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/pi/crypton/server/node_modules/srp/node_modules/bignum
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm verb unsafe-perm in lifecycle true
npm info bignum@0.9.3 Failed to exec install script
npm verb about to build /home/pi/crypton/server/node_modules/srp
npm ERR! bignum@0.9.3 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.9.3 install script.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.0.8-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "link" "--unsafe-perm" "--verbose"
npm ERR! cwd /home/pi/crypton/server
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm verb exit [ 1, true ]
npm verb node_modules/srp/node_modules/bignum unbuild
npm info preuninstall bignum@0.9.3
npm info uninstall bignum@0.9.3
npm verb false,/home/pi/crypton/server/node_modules,/home/pi/crypton/server/node_modules/srp/node_modules unbuild bignum@0.9.3
npm info postuninstall bignum@0.9.3
npm verb node_modules/srp unbuild
npm info preuninstall srp@0.2.0
npm info uninstall srp@0.2.0
npm verb true,/home/pi/crypton/server/node_modules,/home/pi/crypton/server/node_modules unbuild srp@0.2.0
npm info postuninstall srp@0.2.0
npm ERR! not ok code 0
```
How can it be fixed?

**Comment by daviddahl** [comment]
You should use node 12.x instead of 10.x, we should write this into the README, as we don't really support node < 12

**Comment by daviddahl** [comment]
Please join us on irc OFTC.net #crypton if you need more real-time help

I am in CDT (America/Chicago)

**Comment by MTRNord** [comment]
i used the code in the example. how can i update it to 12.x? the explained way installs only this version on wheezy :/ but thanks for help :)

**Comment by daviddahl** [comment]
I use "nvm" to handle multiple versions of node.  
https://github.com/creationix/nvm
Once installed you just do "nvm use 0.12" and it installs it and makes it the default for the current user

**Comment by MTRNord** [comment]
thanks than i will mark it as closed :)

**Comment by MTRNord** [comment]
This way of node install dont work on the pi2 (same problem while compiling) but for others this way helps (at least for me it did):  http://conoroneill.net/download-compiled-version-of-nodejs-0120-stable-for-raspberry-pi-here

**Comment by daviddahl** [comment]
Thanks for the update. Its good to know. Does this current project of yours have a README ?

**Comment by MTRNord** [comment]
In the Crypton dir it has a README.md but not in the server dir and sadly i have to say that this didn't solve the problem. All in all it runs much better but the error is still there. Could it be that the 1GB RAM of the pi2 isn't enough?

**Comment by MTRNord** [comment]
new log: http://pastebin.com/uZxAJGg4

**Comment by daviddahl** [comment]
The fact that it has trouble compiling bignum on that architecture is perhaps the real problem. I would look for the requirements for bignum's dependencies to see what is supported

**Comment by MTRNord** [comment]
would it make any problems to crypton if i dont compile it and use the command "npm install bignum" use?

**Comment by daviddahl** [comment]
you should try that, I have not done that I assume it gives you a JS-native version of it instead of a C implementation?
