### ISSUE TITLE
Bug when I tried to change encryptr password

### ISSUE THREAD

**Issue by Klortho** [SpiderOak/crypton#445]
I don't know if this issue belongs on that repo or this. This was the second thing I tried to do with Encryptr.

```
Uncaught node.js Error 

TypeError: Cannot read property 'toJSON' of undefined
    at changePassphraseCallback (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/Encryptr.js:2218:72)
    at file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:822:9
    at Request.callback (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:7741:3)
    at Request.<anonymous> (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:7466:10)
    at Request.Emitter.emit (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:6952:20)
    at XMLHttpRequest.xhr.onreadystatechange (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:7811:10)
```

**Comment by devgeeks** [comment]
It sounds like a network issue. Is the app still working OK wth the old password, or did the password change but throw the error?

**Comment by Klortho** [comment]
Password changed.
